INSERT INTO gifts (name, url_image, value) values 
("Panela de Pressão Elétrica Electroux", "panela-pressao-eletrica.png", 569.00)
("Lava e seca Samsung", "lava-seca.png", 4099.00),
("Geladeira Electrolux Front Free", "geladeira.png", 5722.00),
("Micro-ondas LG", "micro-ondas.png", 854.00),
("Ferro A Favor", "ferro-passar.png", 322.00),
("Jogo de Copos Americano", "jogo-copo.png", 72.00),
("Jogo de Taças", "jogo-tacas.png", 105.00),
("Jogo de Copos Long Drink", "jogo-copos-drink.png", 54.00),
("Garrafa térmica 100% Inox", "garrafa-termica.png", 399.00),
("Lava-Louças Electrolux", "lava-louca.png", 2999.00),
("Jogo de Toalha 5 peças White", "toalha-white.png", 194.00),
("Jogo de Toalha 5 peças Gray", "toalha-gray.png", 194.00),
("Batedeira Planetária Oster", "batedeira.png", 580.00),
("Jogo de Cama Casal 180 fios", "jogo-cama.png", 360.00),
("Faqueiro Tramontina Laguna em Aço Inox", "faqueiro.png", 260.00),
("Jogo de Jantar Stoneware Orgânico Preto Matte", "prato-jantar-black.png", 856.00),
("Jogo de Jantar Porcela", "prato-jantar-white.png", 230.00),
("Jogo de Jantar Stoneware Bio Breeze", "prato-jantar-blue.png", 626.00),
("Edredom Casal 200 Fios", "edredom.png", 55.00),
("Sofá Cama Del Rey 1,80m", "sofa.png", 3200.00),
("Smart Tv 65'' Crystal UHD 4K", "tv.png", 3214.00),
("Guarda-Roupa Casal 8 Portas Rustic", "guarda-roupa.png", 1800.00),
("Rack Para TV Cedro/Off White", "rack.png", 520.00),
("Armário para Cozinha 7 portas 3 Gavetas", "armario.png", 853.00),
("Manta pra noiva estar sempre coberta de razão", "manta.png", 230.00),
("Claro que posso pagar por esse presente, meu marido tem dois empregos", "rochele.png", 240.00),
("Maracujina para os noivos", "maracujina.png", 59.00),
("Prioridade no quarto de visita dos noivos", "barbie.png", 650.00),
("Deus te iluminou e você decidiu ajudar com a lua de mel do casal", "god.png", 3988.00),
("Aumente suas chances em 33,33% de pegar o buquê", "buque.png", 333.00),
("Cota para a noiva deixar o noivo jogar vídeo game em paz!", "game.png", 220.00),
("Aviãozinho de dinheiro, Maôeeee", "silvio.png", 100.00),
("Truco no time da noiva (Ganhar)", "truco.png", 148.00),
("Patrocínio da despedida de solteiro do noivo!", "despedida-noivo.png", 250.00),
("Patrocínio da despedida de solteiro do noiva!", "despedida-noiva.png", 250.00),
("Jogo de panelas moderno", "jogo-plastico.png", 695.00),
("Primeiro lugar na fila do buffet", "buffet.png", 100.00),
("Cooktop de última geração", "cooktop-plastico.png", 500.00),
("Curso de culinária para o noivo", "jacan.png", 230.00),
("Jantar romântico para os noivos", "jantar.png", 173.00)